# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

head_pose_estimation_demo.dir/gl_camera.cpp.o: common.hpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: freeglut.h
head_pose_estimation_demo.dir/gl_camera.cpp.o: freeglut_ext.h
head_pose_estimation_demo.dir/gl_camera.cpp.o: freeglut_std.h
head_pose_estimation_demo.dir/gl_camera.cpp.o: gl_camera.cpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: gl_camera.hpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: matrix.hpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: matrix_fixed.hpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: rigid_motion.hpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: trackball.hpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: vector.hpp
head_pose_estimation_demo.dir/gl_camera.cpp.o: vector_fixed.hpp

head_pose_estimation_demo.dir/home/wang/desktop/head/CRForestEstimator.cpp.o: /home/wang/desktop/head/CRForest.h
head_pose_estimation_demo.dir/home/wang/desktop/head/CRForestEstimator.cpp.o: /home/wang/desktop/head/CRForestEstimator.cpp
head_pose_estimation_demo.dir/home/wang/desktop/head/CRForestEstimator.cpp.o: /home/wang/desktop/head/CRForestEstimator.h
head_pose_estimation_demo.dir/home/wang/desktop/head/CRForestEstimator.cpp.o: /home/wang/desktop/head/CRTree.h

head_pose_estimation_demo.dir/home/wang/desktop/head/CRTree.cpp.o: /home/wang/desktop/head/CRTree.cpp
head_pose_estimation_demo.dir/home/wang/desktop/head/CRTree.cpp.o: /home/wang/desktop/head/CRTree.h

head_pose_estimation_demo.dir/main.cpp.o: ../CRForest.h
head_pose_estimation_demo.dir/main.cpp.o: ../CRForestEstimator.h
head_pose_estimation_demo.dir/main.cpp.o: ../CRTree.h
head_pose_estimation_demo.dir/main.cpp.o: common.hpp
head_pose_estimation_demo.dir/main.cpp.o: freeglut.h
head_pose_estimation_demo.dir/main.cpp.o: freeglut_ext.h
head_pose_estimation_demo.dir/main.cpp.o: freeglut_std.h
head_pose_estimation_demo.dir/main.cpp.o: gl_camera.hpp
head_pose_estimation_demo.dir/main.cpp.o: main.cpp
head_pose_estimation_demo.dir/main.cpp.o: matrix.hpp
head_pose_estimation_demo.dir/main.cpp.o: matrix_fixed.hpp
head_pose_estimation_demo.dir/main.cpp.o: rigid_motion.hpp
head_pose_estimation_demo.dir/main.cpp.o: vector.hpp
head_pose_estimation_demo.dir/main.cpp.o: vector_fixed.hpp
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/Linux-Arm/../Linux-x86/XnPlatformLinux-x86.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/Linux-Arm/XnPlatformLinux-Arm.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/Linux-x86/XnOSLinux-x86.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/Linux-x86/XnPlatformLinux-x86.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/MacOSX/XnPlatformMacOSX.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnCodecIDs.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnContext.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnCppWrapper.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnEnumerationErrors.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnLicensing.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnMacros.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnModuleInterface.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnOS.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnOSMemory.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnOSStrings.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnOpenNI.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnPlatform.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnPrdNode.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnPrdNodeInfo.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnPrdNodeInfoList.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnQueries.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnStatus.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnStatusCodes.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnTypes.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnUtils.h
head_pose_estimation_demo.dir/main.cpp.o: /usr/include/ni/XnVersion.h

