# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -O3 -DNDEBUG -I/home/wang/desktop/head/demo/. -I/home/wang/desktop/head/demo/.. -I/usr/include/ni -I/include  

CXX_DEFINES = 

